### ISSUE TITLE
Can not load "minimalist", it is not registered!

### ISSUE THREAD

**Issue by op1ekun** [inspector-ambitious/karma-minimalist-reporter#3]
Hi,

the minimalist is installed in my  devDependencies:
`"karma-minimalist-reporter": "^0.2.0"`

and configured in my karma.conf.json:
`reporters: ['minimalist'],`

and I get:
`WARN [reporter]: Can not load "minimalist", it is not registered!`

**Comment by feeela** [comment]
This issue is still valid. @op1ekun  Why was it closed? How is the fix to get this reporter up an running?

**Comment by op1ekun** [comment]
Honestly I've used a different reporter since then.
